### ISSUE TITLE
Составление ТЗ и плана работ

### ISSUE THREAD

**Issue by evgeny-p** [ri57-sibsutis/alphabet#1]
Примерное содержание ТЗ доступно в [статье](http://evgeny-p.github.io/teaching/materials/project/02-planning.html).

Definition of Done:
1. В [wiki](https://github.com/ri57-sibsutis/alphabet/wiki) проекта написана статья с ТЗ.
2. В [issues](https://github.com/ri57-sibsutis/alphabet/issues) созданы задачи.
3. ТЗ и план приняты заказчиком.

По готовности оставить комментарий в этой задаче.

**Comment by Korna** [comment]
@evgeny-p Прошу посмотреть первую версию ТЗ и декомпозицию на задачи
